version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/home/node/app
      -  /home/node/app/node_modules