FROM node:22-slim 
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node . .
ENV DOCKER_ENV=true
CMD [ "npm","run","dev"]