version: "3"
services:
  nginx:
    image: 'ronhachmon/cut-nginx'
    ports:
      - "80:80"
    mem_limit : 512m
    hostname: nginx
  api:
    image: 'ronhachmon/cut-server'
    hostname: api
    mem_limit : 512m
    restart : on-failure
  client:
    image: 'ronhachmon/cut-client'
    mem_limit : 512m
    hostname: client