name: Deploy images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: cut-it-out
          environment_name: Cut-it-out-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-858189250353
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
